# Generated by Django 6.0.5 on 2026-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('rating', models.FloatField()),
                ('stock', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('sku', models.CharField(max_length=100)),
                ('warranty_information', models.CharField(max_length=255)),
                ('shipping_information', models.CharField(max_length=255)),
                ('availability_status', models.CharField(max_length=100)),
                ('return_policy', models.CharField(max_length=255)),
                ('minimum_order_quantity', models.IntegerField()),
            ],
        ),
    ]
